### PR TITLE
Updating Team Page section

### PR DESCRIPTION
**Pull request by romeboards**
**This is a simple starting point for changing the team page accordions** - we can keep this PR open if we want until everything is in place.

I proposed just aligning the desktop version with the mobile version (which auto collapses the sections) to see what we would want to do in addition to this. Maybe good for a preview/demo version?

### CODE REVIEW

**Comment by romeboards** [comment]
@ghostwords could you deploy this to the demo site as well for @LindseyWagner to mess around with? I want to explore this nested accordion structure more... thanks!

**Comment by ghostwords** [comment]
Deployed.

**Comment by LindseyWagner** [comment]
see it.

good start. you want to just make the titles linkable? we'd need to make
them orange. are you gonna make em close if another is clicked? or is that
too much?

**Comment by romeboards** [comment]
1. Can definitely make them one open at-a-time
2. Would you just want to change the style of the titles to be orange? Should they still underline on hover? Ex:

image

Also still unclear on the new structure of the page... is there going to be a secondary level of collapsable things?

**Comment by LindseyWagner** [comment]
Hey!

- def open one at a time
- def underline on hover

I think the font size should also be knocked down to something closer to
paragraph. On the other pages the size of the H5 looks nice. what is the
style/size you have on them now?

By showing all the finding america projects as links, i don't need a nested
structure anymore.

**Comment by LindseyWagner** [comment]
You don't have a title though above the finding america projects --- which
is different than what i mocked. Also see Ryan's email for language updates.

**Comment by romeboards** [comment]
@ghostwords worked with Lindsey to update this - she says we can push this (as well as #4) to the live site

**Comment by ghostwords** [comment]
@romeboards @LindseyWagner Updates are live.

**Comment by romeboards** [comment]
Thanks!

**Pull request merged**
